export enum Operator {
  Plus = '+',
  Asterik = '*',
  Minus = '-',
  Slash = '/',
  PercentSign = '%',
  LessThan = '<',
  GreaterThan = '>',
  LessThanOrEqual = '<=',
  GreaterThanOrEqual = '>=',
  NotEqual = '!=',
  Equal = '==',
  Or = 'or',
  And = 'and',
  Not = 'not',
  AddShorthand = '+=',
  SubtractShorhand = '-=',
  MultiplyShorthand = '*=',
  DivideShorthand = '/=',
  BitwiseAnd = '&',
  BitwiseOr = '|',
  Xor = '^',
  LeftShift = '<<',
  RightShift = '>>',
  UnsignedRightShift = '>>>'
}
